version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:latest
    environment:
      postgres_db: db_url_shortener
      postgres_user: user
      postgres_password: password
      ports:
        - "5432:5432"

      redis:
        image: redis:latest
        ports:
          - "6379:6379"
